<a href="https://colab.research.google.com/github/ucekadrianarm-art/-LGEBRA_LINEAL_UCE/blob/main/ALGEBRA_UNIDAD_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cáculo de la matriz transpuesta, adjunta e inversa

## Matriz Transpuesta

La matriz transpuesta de una matriz $A$, denotada por $A^T$ o $A'$, es una matriz obtenida al cambiar sus filas por columnas y sus columnas por filas.

Si $A$ es una matriz de $m \times n$, entonces $A^T$ es una matriz de $n \times m$. Formalmente, si $A = (a_{ij})$, entonces $A^T = (a_{ji})$.

**Ejemplo:**

Si
$$
A = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{pmatrix}
$$
Entonces
$$
A^T = \begin{pmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{pmatrix}
$$

**Propiedades de la matriz transpuesta:**

* $(A^T)^T = A$
* $(A + B)^T = A^T + B^T$
* $(\alpha A)^T = \alpha A^T$, donde $\alpha$ es un escalar.
* $(AB)^T = B^T A^T$

In [1]:
import numpy as np

# Crear una matriz de ejemplo de n x m (por ejemplo, 2x3)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Matriz original ({}x{}):".format(A.shape[0], A.shape[1]))
print(A)

# Calcular la matriz transpuesta
A_T = A.T

print("\nMatriz transpuesta ({}x{}):".format(A_T.shape[0], A_T.shape[1]))
print(A_T)

# Puedes cambiar las dimensiones de la matriz para probar
# A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) # Ejemplo de matriz 3x4
# A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]]) # Ejemplo de matriz 4x2

Matriz original (2x3):
[[1 2 3]
 [4 5 6]]

Matriz transpuesta (3x2):
[[1 4]
 [2 5]
 [3 6]]


## Matriz Adjunta

La matriz adjunta de una matriz cuadrada $A$, denotada por $\text{adj}(A)$, es la transpuesta de la matriz de cofactores de $A$.

La matriz de cofactores se obtiene reemplazando cada elemento $a_{ij}$ de la matriz original por su cofactor $C_{ij}$, donde el cofactor se calcula como $C_{ij} = (-1)^{i+j} M_{ij}$. $M_{ij}$ es el menor, que es el determinante de la submatriz que resulta de eliminar la fila $i$ y la columna $j$.

Formalmente: $\text{adj}(A) = (C_{ij})^T$

**Ejemplo para una matriz 2x2:**

Si
$$
A = \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
$$

La matriz de cofactores es:
$$
\begin{pmatrix}
d & -c \\
-b & a
\end{pmatrix}
$$

La matriz adjunta es la transpuesta de la matriz de cofactores:
$$
\text{adj}(A) = \begin{pmatrix}
d & -b \\
-c & a
\end{pmatrix}
$$

In [2]:
import numpy as np

# Función para calcular el determinante de una matriz 2x2
def determinante_2x2(matrix):
    return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]

# Función para obtener la submatriz (para calcular menores)
def obtener_submatriz(matrix, fila, columna):
    return np.delete(np.delete(matrix, fila, axis=0), columna, axis=1)

# Crear una matriz de ejemplo 3x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Matriz original:")
print(A)

# Calcular la matriz de cofactores
cofactor_matrix = np.zeros_like(A, dtype=float)

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        # Obtener la submatriz
        submatrix = obtener_submatriz(A, i, j)

        # Calcular el menor (determinante de la submatriz)
        if submatrix.shape == (2, 2):
             menor = determinante_2x2(submatrix)
        else:
             # Para matrices de tamaño > 2x2, se necesitaría una función de determinante general
             # Para este ejemplo 3x3, solo necesitamos el caso 2x2
             pass # Esto no debería ocurrir para una matriz 3x3 al eliminar una fila y columna

        # Calcular el cofactor
        cofactor = ((-1)**(i + j)) * menor

        # Asignar el cofactor a la matriz de cofactores
        cofactor_matrix[i, j] = cofactor

print("\nMatriz de cofactores:")
print(cofactor_matrix)

Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz de cofactores:
[[ -3.   6.  -3.]
 [  6. -12.   6.]
 [ -3.   6.  -3.]]


## Matriz Inversa a través de la Adjunta

Una matriz cuadrada $A$ tiene una inversa, denotada por $A^{-1}$, si y solo si su determinante ($\det(A)$) no es cero. Si el determinante es cero, la matriz es singular y no tiene inversa.

Cuando una matriz $A$ es invertible, su inversa $A^{-1}$ se puede calcular utilizando la matriz adjunta de la siguiente manera:

$$
A^{-1} = \frac{1}{\det(A)} \text{adj}(A)
$$

Donde:
* $A^{-1}$ es la matriz inversa de $A$.
* $\det(A)$ es el determinante de la matriz $A$.
* $\text{adj}(A)$ es la matriz adjunta de $A$ (la transpuesta de la matriz de cofactores).

Para calcular la matriz inversa usando este método, se siguen los siguientes pasos:

1. **Calcular el determinante de la matriz A.** Si $\det(A) = 0$, la matriz no tiene inversa.
2. **Calcular la matriz de cofactores de A.** Reemplazar cada elemento $a_{ij}$ por su cofactor $C_{ij}$.
3. **Calcular la matriz adjunta de A.** Transponer la matriz de cofactores.
4. **Multiplicar la matriz adjunta por el inverso del determinante.** Dividir cada elemento de la matriz adjunta por el determinante de $A$.

Este método es conceptualmente importante y útil para matrices pequeñas (como 2x2 o 3x3). Para matrices más grandes, existen métodos computacionalmente más eficientes para encontrar la inversa.

In [3]:
import numpy as np

# Función para calcular el determinante de una matriz 2x2 (reutilizada del código anterior)
def determinante_2x2(matrix):
    return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]

# Función para obtener la submatriz (para calcular menores) (reutilizada del código anterior)
def obtener_submatriz(matrix, fila, columna):
    return np.delete(np.delete(matrix, fila, axis=0), columna, axis=1)

# Función para calcular el determinante de una matriz 3x3
def determinante_3x3(matrix):
    det = 0
    for j in range(matrix.shape[1]):
        det += ((-1)**j) * matrix[0, j] * determinante_2x2(obtener_submatriz(matrix, 0, j))
    return det

# Función para calcular la matriz de cofactores de una matriz 3x3
def matriz_cofactores_3x3(matrix):
    cofactor_matrix = np.zeros_like(matrix, dtype=float)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            submatrix = obtener_submatriz(matrix, i, j)
            menor = determinante_2x2(submatrix)
            cofactor = ((-1)**(i + j)) * menor
            cofactor_matrix[i, j] = cofactor
    return cofactor_matrix

# Crear una matriz de ejemplo 3x3 (cambia los valores si quieres probar con otra matriz)
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

print("Matriz original:")
display(A)

# 1. Calcular el determinante de A
det_A = determinante_3x3(A)
print(f"\nDeterminante de A: {det_A}")

# Verificar si la matriz es invertible
if det_A == 0:
    print("\nLa matriz no tiene inversa ya que su determinante es cero.")
else:
    # 2. Calcular la matriz de cofactores de A
    cofactor_A = matriz_cofactores_3x3(A)
    print("\nMatriz de cofactores de A:")
    display(cofactor_A)

    # 3. Calcular la matriz adjunta de A (transpuesta de la matriz de cofactores)
    adj_A = cofactor_A.T
    print("\nMatriz adjunta de A:")
    display(adj_A)

    # 4. Calcular la matriz inversa de A
    A_inv = (1 / det_A) * adj_A
    print("\nMatriz inversa de A:")
    display(A_inv)

    # Opcional: Verificar la inversa (A * A_inv debería ser la matriz identidad)
    identidad = np.dot(A, A_inv)
    print("\nVerificación (A * A_inv):")
    display(identidad)

Matriz original:


array([[1, 2, 3],
       [0, 1, 4],
       [5, 6, 0]])


Determinante de A: 1

Matriz de cofactores de A:


array([[-24.,  20.,  -5.],
       [ 18., -15.,   4.],
       [  5.,  -4.,   1.]])


Matriz adjunta de A:


array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])


Matriz inversa de A:


array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])


Verificación (A * A_inv):


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])